---
name: VisibleAutoPickup
main: kim\present\visibleautopickup\Main
version: 1.1.2
api: [ 5.0.0 ]
author: PresentKim
description: Automatically picks up items and xp orbs before others pick them up!
...